name: GitHub Maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Run daily at 03:00

jobs:
  github_maintenance:
    name: Execute Maintenance
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Delete workflow runs
        uses: viascom/github-maintenance-action@v0.0.1